name: RefreshBindings
description: Script to refresh bindings
# version: 1.0.0
# homepage: https://www.kdab.com
environment:
  sdk: '>=3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

dependencies:
  path: ^1.7.0
