# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2022
          - windows-2019
          - macos-12
          - macos-11
        preset:
          - name: ci-dev-qt5
            qt_version: "5.15"
          - name: ci-release-qt5
            qt_version: "5.15"
          - name: ci-qtwidgets-qt5
            qt_version: "5.15"
          - name: ci-qtquick-qt5
            qt_version: "5.15"
          - name: ci-dev-qt6
            qt_version: "6.3.*"
          - name: ci-release-qt6
            qt_version: "6.3.*"
          - name: ci-qtwidgets-qt6
            qt_version: "6.3.*"
          - name: ci-qtquick-qt6
            qt_version: "6.3.*"
        include:
          - os: ubuntu-22.04
            preset:
              name: ci-dev-asan-qt5
              qt_version: "5.15"
              detect_leaks: 0
          - os: ubuntu-22.04
            preset:
              name: ci-dev-asan-qtwidgets-qt6
              qt_version: "6.5.*"
              detect_leaks: 1
          - os: ubuntu-22.04
            preset:
              name: ci-dev-asan-qtquick-qt6
              qt_version: "6.5.*"
              detect_leaks: 1
          - os: ubuntu-22.04
            preset:
              name: ci-clang-tidy-qt5
              qt_version: "5.15"

    steps:
      - name: Install Qt ${{ matrix.preset.qt_version }} with options and default aqtversion
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.preset.qt_version }}
          cache: true

      - name: Install dependencies on Ubuntu
        if: ${{ runner.os == 'Linux' && startsWith(matrix.preset.name, 'ci-dev-asan') }}
        run: |
          sudo apt update -qq
          sudo apt install -y lld

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure project
        run: cmake -S . -B ./build --preset ${{ matrix.preset.name }}

      - name: Build Project
        run: cmake --build ./build

      - name: Run tests on Linux (offscreen)
        if: ${{ startsWith(matrix.preset.name, 'ci-dev-') && runner.os == 'Linux' }}
        run: ctest --test-dir ./build --output-on-failure
        env:
          QT_QPA_PLATFORM: offscreen
          QT_QUICK_BACKEND: software
          LSAN_OPTIONS: detect_leaks=${{ matrix.preset.detect_leaks }}

      - name: Run tests on Window/macOS
        if: ${{ startsWith(matrix.preset.name, 'ci-dev-') && runner.os != 'Linux' }}
        run: ctest --test-dir ./build --output-on-failure

      - name: Read tests log when it fails
        uses: andstor/file-reader-action@v1
        if: ${{ failure() && startsWith(matrix.preset.name, 'ci-dev-') }}
        with:
          path: "./build/Testing/Temporary/LastTest.log"
