# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

# Builds the flutter frontend
# Doesn't run tests yet though

name: Flutter-dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        preset:
          - name: dev-flutter
            isAOT: false
            args: []
          # - name: dev-flutter-asan
          #   isAOT: false
          #   args: ["--asan"]
          # - name: dev-flutter-aot
          #   isAOT: true
          #   args: ["--aot"]
          # - name: dev-flutter-aot-asan
          #   isAOT: true
          #   args: ["--aot", "--asan"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt update -qq
          sudo apt install libgtk-3-dev libglib2.0-dev ninja-build libspdlog-dev lld xvfb -y

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Configure project ${{ matrix.preset.name }}
        run: cmake -S . -B ./build-${{ matrix.preset.name }} --preset ${{ matrix.preset.name }}

      - name: Build Project ${{ matrix.preset.name }}
        run: cmake --build ./build-${{ matrix.preset.name }}

      - name: Build the example
        run: |
          cd examples/flutter
          flutter build linux

      - name: Run tests
        run: |
          cd ${{ github.workspace }}/src/flutter/dart
          flutter pub get
          cd ${{ github.workspace }}/tests/flutter/
          flutter pub get
          cd ${{ github.workspace }}/build-dev-flutter/
          ctest --output-on-failure
        env:
          KDDW_BINDINGS_LIB: ${{ github.workspace }}/build-dev-flutter/lib/libkddockwidgets.so
