# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: LSAN Qt6

on:
  push:
    branches:
      - 2.1
      - main
  pull_request:
    branches:
      - 2.1
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        preset:
          - name: ci-dev-asan-qtwidgets-qt6
            qt_version: "6.7.0"
          - name: ci-dev-asan-qtquick-qt6
            qt_version: "6.7.0"

    steps:

      - name: Workaround installer bug when using 6.7
        run: |
          mkdir -p /home/runner/work/KDDockWidgets/Qt/${{ matrix.preset.qt_version }}/gcc_64
          ln -sf /home/runner/work/KDDockWidgets/Qt/${{ matrix.preset.qt_version }}/gcc_64 /home/runner/work/KDDockWidgets/Qt/${{ matrix.preset.qt_version }}/linux_gcc_64

      - name: Install Qt ${{ matrix.preset.qt_version }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.preset.qt_version }}
          cache: true
          arch: linux_gcc_64

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt update -qq
          sudo apt install lld libspdlog-dev ninja-build -y

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake -S . -B ./build-${{ matrix.preset.name }} --preset ${{ matrix.preset.name }}

      - name: Build Project ${{ matrix.preset.build_preset_arg }}
        run: cmake --build ./build-${{ matrix.preset.name }} ${{ matrix.preset.build_preset_arg }}

      - name: Run tests on Linux (offscreen)
        run: ctest --test-dir ./build-${{ matrix.preset.name }} --output-on-failure
        env:
          QT_QPA_PLATFORM: offscreen
          QT_QUICK_BACKEND: software
          LSAN_OPTIONS: detect_leaks=1

      - name: Read tests log when it fails
        uses: andstor/file-reader-action@v1
        if: ${{ failure() && startsWith(matrix.preset.name, 'ci-dev-') }}
        with:
          path: "./build-${{ matrix.preset.name }}/Testing/Temporary/LastTest.log"
